/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 12/10/2012, 23:28:22
 */
package br.com.Wiu;

import br.com.Pedidos.Pedidos;
import br.com.sisvenda.vendas.MudaSenha;
import conexao.LerProperties;
import java.awt.Container;
import java.awt.Toolkit;
//import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


    /**
 *
 * @author rox
 */
public final class Principal extends javax.swing.JFrame {
    
    double total = 0;
    double Result = 0;
    private Container c; 
    
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/icones/vendas.gif")));
       // setExtendedState(MAXIMIZED_BOTH); 
        setExtendedState(MAXIMIZED_BOTH); // tela maximizado
        //Entra();
        Entrar();
        //java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        //setBounds((screenSize.width-994)/2, (screenSize.height-859)/2, 820, 790);
    }                                                  //altura   //largura //comprimento

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        sai = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCli = new javax.swing.JMenuItem();
        jMenuPedidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuCardapio = new javax.swing.JMenuItem();
        jMenuTeclado = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        lbPrincipal = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuVendas = new javax.swing.JMenuItem();
        jMenuVendasDog = new javax.swing.JMenuItem();
        jMenuJuros = new javax.swing.JMenuItem();
        jMenuRenda = new javax.swing.JMenuItem();
        jMenuSenha = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Vendas e Pedidos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data da Operacao"));

        lbdata.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbdata.setForeground(new java.awt.Color(0, 204, 102));
        lbdata.setText("....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbdata, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbdata, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/cantinhodog_logo.png"))); // NOI18N
        jLabel1.setText("...");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/icones/sair.gif"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        jRadioButton1.setText("COMEÇE A SEQUENCIA DOS PEDIDOS AQUI!");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Cantinho_do_Dog");

        jLabel3.setText("CantinhoDog @ todos os direitos reservados|  06/09/2022");

        jMenu1.setText("Arquivo");

        jMenuItem3.setText("Sobre o Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        sai.setText("Sair");
        sai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saiActionPerformed(evt);
            }
        });
        jMenu1.add(sai);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registrar");

        jMenuCli.setText("Cadastro de Clientes");
        jMenuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCliActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCli);

        jMenuPedidos.setText("Cadastro de Pedidos");
        jMenuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPedidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menu Principal");

        jMenuItem1.setText("Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Utilitarios");

        jMenuItem2.setText("Calculadora");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuCardapio.setText("Cardapio");
        jMenuCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCardapioActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCardapio);

        jMenuTeclado.setText("Teclado Virtual");
        jMenuTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTecladoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuTeclado);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Operador");

        lbPrincipal.setText("...");
        jMenu5.add(lbPrincipal);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Administração");

        jMenuVendas.setText("Relatorio Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuVendas);

        jMenuVendasDog.setText("Vendas");
        jMenuVendasDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasDogActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuVendasDog);

        jMenuJuros.setText("CalcJuros");
        jMenuJuros.setToolTipText("Calcula juros");
        jMenuJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuJurosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuJuros);

        jMenuRenda.setText("IRPF");
        jMenuRenda.setToolTipText("Calculo Impoto Renda");
        jMenuRenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRendaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuRenda);

        jMenuSenha.setText("AterarSenha");
        jMenuSenha.setToolTipText("Altera a senha que utiliza para excluir as vendas");
        jMenuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSenhaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuSenha);

        jMenuItem4.setText("Atualizações");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuPedido.setText("Pedidos");
        jMenuPedido.setToolTipText("Visualizar os pedidos");
        jMenuPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuPedido);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizaagora();
    }//GEN-LAST:event_formWindowOpened
     
     
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ProcessBuilder builder = new ProcessBuilder("C:\\Windows\\System32\\calc.exe");
         try {builder.start();
         } catch (IOException e) {
             //e.printStackTrace();
         }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
   
    

  
  
/** 
 * Remove a linha pelo valor da coluna informada 
 * @param val 
 * @param col 
 * @return 
 */  


        
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        
        JOptionPane.showMessageDialog(null, "O Sistema de Vendas Facil, Auxilia no controle de pedidos "+"\n"+" Controlam os pedidos em fila, como anotações criadas em uma GRADE armazenadas no PC em forma de blocos de anotações,"+"\n"+""+"\n"+"Duvidas ou sugestões Sistema de Vendas - digaotekwodo@hotmail.com"+"\n"+"Rodrigo Luiz Xavier : Celular (41)988503864");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null,"Deseja Sair do SISTEMA? Cuidado!!! Essa acao nao GRAVA os pedidos de venda no BANCO")==JOptionPane.OK_OPTION){  
            
            sair();
            
           
           //System.exit(0);
        }   
    }//GEN-LAST:event_btSairActionPerformed

    private void saiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saiActionPerformed
        
       if (JOptionPane.showConfirmDialog(null,"Deseja Sair do SISTEMA? Cuidado!!! Essa acao nao GRAVA os pedidos de venda")==JOptionPane.OK_OPTION){  
            
            sair();
            
           
           //System.exit(0);
        }   
    }//GEN-LAST:event_saiActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
       
        if (jRadioButton1.isSelected()== true) {
            Pedidos ped = new Pedidos();   
           // c = getContentPane();  
            //c.add(ped, BorderLayout.BEFORE_FIRST_LINE);  
            //setBounds(100,100,500,500); 
            Pedidos.pedir.setText("1.0");
            Pedidos.jMenuOperador.setText(lbPrincipal.getText());
            //Pedidos.opera.setText(lbPrincipal.getText());
            ped.setVisible(true); 
        }else{
            //Principal.txtAcesso.setText(con_usuario.resultset.getString("Auditoria_usu"));
            
            //Pedidos.pedir.setText(("Pedido Nº")+Pedidos.pedir);
            //ped.setVisible(true);  
            jRadioButton1.setEnabled(false);
       }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jMenuPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoActionPerformed
        try {
             //---java.awt.Desktop.getDesktop().open( new File( "C:/pedido/pedidos.txt" ) );
             java.awt.Desktop.getDesktop().open( new File( "C:/pedido/tela.txt" ) );
            //JOptionPane.showMessageDialog(null, "Visualize o pedido");  
            } catch (IOException e) {
             //e.printStackTrace();
         }
            
    }//GEN-LAST:event_jMenuPedidoActionPerformed

    private void Volante(){
        
        try{
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/icones/vale.jpg")));
        
            } catch (NumberFormatException ex) {
             JOptionPane.showMessageDialog(null, "Erro" + ex); 
         }
        
        //URL imgUrl = this.getClass().getResource("src/br/com/icones/pedidos.jpg");
}


    private void jMenuCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCardapioActionPerformed
        //java.awt.Desktop.getDesktop().open( new File( "c:/pedido/cardapio.jpg" ) );
        //JOptionPane.showMessageDialog(null, "Entrada", JOptionPane.PLAIN_MESSAGE);
                      Volante();
    }//GEN-LAST:event_jMenuCardapioActionPerformed

    private void jMenuTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTecladoActionPerformed
       try {
            java.awt.Desktop.getDesktop().open( new File( "C:/Windows/system32/osk.exe" ) );
            //JOptionPane.showMessageDialog(null, "Visualize o pedido");  
        } catch (IOException e) {
             JOptionPane.showMessageDialog(null, "Erro" + e); 
         }
    }//GEN-LAST:event_jMenuTecladoActionPerformed

    private void jMenuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCliActionPerformed
        Clientes clientes = new Clientes();
           
         clientes.setVisible(true);
    }//GEN-LAST:event_jMenuCliActionPerformed

    private void jMenuVendasDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasDogActionPerformed
        VendasDog venda = new  VendasDog();
          venda.setVisible(true);
    }//GEN-LAST:event_jMenuVendasDogActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
          ImpressaoView visao = new ImpressaoView();
          visao.setVisible(true);
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuJurosActionPerformed
        CalcJuros juros = new CalcJuros ();
        juros.setVisible(true);
    }//GEN-LAST:event_jMenuJurosActionPerformed

    private void jMenuRendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRendaActionPerformed
        CalcRenda renda = new CalcRenda();
        renda.setVisible(true);
    }//GEN-LAST:event_jMenuRendaActionPerformed

    private void jMenuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSenhaActionPerformed
        ConsultaAcesso();
    }//GEN-LAST:event_jMenuSenhaActionPerformed

    private void jMenuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPedidosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       JOptionPane.showMessageDialog(null, 
               
                  ""
                  +"\n"+"Atualizado | 06/09/2022, Preços, Banco"+"\n"+""
                  +"\n"+"Atualizado | 07/11/2018, Impressora Epson USB"+"\n"+""
                  +"\n"+"Atualizado | 10/08/2019, adicionado X-Gourmet, e clientes"+"\n"+""
                   + "//localhost//EPSON TM-T20,"+"\n"+""+"\n"+"");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void sair() {
        //dispose();
         System.exit(0);
     
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private void ConsultaAcesso(){
        //objeto que vai armazenar a variavel digitada
        JPasswordField jpassword = new JPasswordField(); 
        jpassword.requestFocus();
        if (JOptionPane.showConfirmDialog (null, jpassword, "Entre com a senha", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {  
            //System.out.println (new String(jpassword.getPassword()));
            //pega o texto digitado
            
        if (jpassword.getText().equals(LerProperties.lerProperties("urlBanco"))){
            //if (lbUsuarios.getText().equals("Andre Gouveia")|| lbUsuarios.getText().equals("Tony")){
            //System.exit(0);
            JOptionPane.showMessageDialog(null,"Seja bem vindo! Lembre-se da nova senha!");
           
            //mostraCadastro();
            MudaSenha mostra = new MudaSenha();
            mostra.show(); 
        //CapturaFotos d = new CapturaFotos();//cria objeto e armazena na variavel d.show
        //d.show();
       // CapturaImagens d = new CapturaImagens();//cria objeto e armazena na variavel d.show
       // d.show();
       // Cadastrar d = new Cadastrar();//classe Cadastrar
       // d.show();
        
        }else{
            //mostrarVeiculos();
            //Veiculos.tfatualizacao.setText(lbUsuarios.getText());//gravando no label lbatualizacao
            //JOptionPane.showMessageDialog(null,"Assim não da, TCHAU");
            String e ="Atencao";
            JOptionPane.showMessageDialog(null,"Assim não da"+e,"ATENTE PARA SUA",JOptionPane.WARNING_MESSAGE);
            //dispose();
        //pega o texto gravado em lbUsuarios e seta no campo tfatualizacao
          }
    
        }
        
    }
    public void Entrar(){  
  
        // Cria campo onde o usuario entra com a senha  
        JTextField password = new JTextField(10); 
        //JPasswordField password = new JPasswordField(10); 
        
        //password.setEchoChar('*');   //faz prencher com esses caracter
        password.setToolTipText("Entre com o seu Nome"); 
       // password.setFocusable(rootPaneCheckingEnabled);
        //password.requestFocus(true);
        
        
        // Cria um rótulo para o campo  
        JLabel rotulo = new JLabel("Operador:");  
                  
        // Coloca o rótulo e a caixa de entrada numa JPanel:  
        JPanel entUsuario = new JPanel();  
        entUsuario.add(rotulo);  
        entUsuario.add(password);
        //entUsuario.add(password);
        //jMenuTecladoActionPerformed(entUsuario);
        //InputMap imap =
       // InputMap inputMap = password.getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        // Mostra o rótulo e a caixa de entrada de password para o usuario fornecer a senha:  
        JOptionPane.showMessageDialog(null, entUsuario, "Entrada",JOptionPane.PLAIN_MESSAGE);  
       // JOptionPane.showInputDialog(null, entUsuario, "Acesso Restrito",JOptionPane.INFORMATION_MESSAGE);  
        // O programa só prossegue quando o usuário clicar o botao de OK do showMessageDialog.   
        // Aí, é só pegar a senha:  
  
        // Captura a senha:  
        String senha = password.getText();
         //password.setText("cc");
        if ("".equals(senha)){//se a variavel senha for vazio
            JOptionPane.showMessageDialog(null, "Campo vazio Sistema não encontrado");
            System.exit(0);
        }else{
            ////se nao a variavel senha for prenchida
            //JOptionPane.showMessageDialog(null, "Campo preenchido Sistema a Iniciar");
        }
  
        // mostra a senha no terminal:  
        //System.out.println("Você digitou: "+senha+"\nFim de execucao.");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //DESABILITA O X NO FORMULÁRIO 
        //setBounds(150,55,900,600);//redimensiona o form lado,altura,largura,comprimento
         
        //Principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lbPrincipal.setText(senha);//grava o operador
    } 
    private void atualizaagora(){
    String FormatData = new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis()));
    //tfDatahoje.setText(FormatData);//passa por parametro a data atual
    //tfDataAtual.setText(FormatData);
    lbdata.setText(FormatData);
}
    public void Entra(){     
         
        
         passa p = new passa();  
      // FOR QUE INSERE OS 10 NOMES DENTRO DO VETOR CHAMADO LISTA     
         for(int i = 0; i < p.getLista().length;i++){     
         p.setListaItem(JOptionPane.showInputDialog("Digite o nome do Operador"),i);     
              
      } 
                   
      // FOR QUE IMPRIME OS 2 NOMES INSERIDOS NA ORDEM NA QUAL FORAM INSERIDOS     
          for(int i = 0; i < p.getLista().length;i++){     
         //System.out.println(p.getListaItem(i)); 
         lbPrincipal.setText(p.getListaItem(i));//grava o operador
          
              
      } 
      
       
    }
   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCardapio;
    private javax.swing.JMenuItem jMenuCli;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuJuros;
    private javax.swing.JMenuItem jMenuPedido;
    private javax.swing.JMenuItem jMenuPedidos;
    private javax.swing.JMenuItem jMenuRenda;
    private javax.swing.JMenuItem jMenuSenha;
    private javax.swing.JMenuItem jMenuTeclado;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JMenuItem jMenuVendasDog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JMenuItem lbPrincipal;
    private javax.swing.JLabel lbdata;
    private javax.swing.JMenuItem sai;
    // End of variables declaration//GEN-END:variables

    
}
