/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VendasDog.java
 *
 * Created on 18/01/2014, 21:34:39
 */
package br.com.Wiu;

import br.com.sisvenda.vendas.VendasBean;
import br.com.sisvenda.vendas.VendasControl;
import conexao.LerProperties;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.text.DateFormat;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROX
 */
public class VendasDog extends javax.swing.JFrame {
   
    DefaultTableModel tmServidores = new DefaultTableModel(null, new String[]{"Codigo", "Itens", "DataVenda", "Pedido","Recebido","Troco","Valor"});
    ListSelectionModel lsmServidores;
    List<VendasBean> servidores;
    List<VendasBean> produtos;
    List<VendasBean> vendas;
    Object calcula;

    /** Creates new form VendasDog */
    public VendasDog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtConsulta = new JFormattedTextField(DateFormat.getDateInstance());
        ftfTotal = new JFormattedTextField(DateFormat.getDateInstance());
        jLabel2 = new javax.swing.JLabel();
        btPesquisa = new javax.swing.JButton();
        txtConsultaFim = new JFormattedTextField(DateFormat.getDateInstance());
        jScrollPane1 = new javax.swing.JScrollPane();
        tbServidores = new javax.swing.JTable();
        contacli = new javax.swing.JLabel();
        btPesquisas = new javax.swing.JButton();
        btSomar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas Vendas");

        jLabel1.setText("Consultas");

        txtConsulta.setToolTipText("Data inicial");
        txtConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsultaMouseClicked(evt);
            }
        });

        ftfTotal.setEditable(false);
        ftfTotal.setFont(new java.awt.Font("Tahoma", 1, 24));

        jLabel2.setText("Total - R$");

        btPesquisa.setText("Pesquisa");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        txtConsultaFim.setToolTipText("Data inicial");
        txtConsultaFim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsultaFimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConsultaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisa)
                .addGap(146, 146, 146)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtConsultaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ftfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbServidores.setModel(tmServidores);
        tbServidores.setToolTipText("Clique na Tabela para dar a Soma total do dia");
        tbServidores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmServidores = tbServidores.getSelectionModel();
        lsmServidores.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    tbClientesLinhaSelecionada(tbServidores);
                }
            }
        });
        jScrollPane1.setViewportView(tbServidores);

        contacli.setText("......");

        btPesquisas.setText("Pesquisa Tudo");
        btPesquisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisasActionPerformed(evt);
            }
        });

        btSomar.setText("Somar");
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Venda");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contacli, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btPesquisas)
                        .addGap(18, 18, 18)
                        .addComponent(btSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(contacli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btPesquisas)
                    .addComponent(btSomar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisasActionPerformed
       listarVendas();
        //pesquisarVendas();
    }//GEN-LAST:event_btPesquisasActionPerformed

    private void txtConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultaMouseClicked
       atual();
    }//GEN-LAST:event_txtConsultaMouseClicked

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        pesquisarVendas();
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void txtConsultaFimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultaFimMouseClicked
        //pesquisarVendas();
        atualFim();
    }//GEN-LAST:event_txtConsultaFimMouseClicked
    private void LimpaCampos(){
        txtConsulta.setText(null);
        txtConsultaFim.setText(null);
    }
    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed
        listarCalculoVendas();
        LimpaCampos();
    }//GEN-LAST:event_btSomarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        //excluirVenda();
        ConsultaExcluir() ;
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VendasDog().setVisible(true);
            }
        });
    }
    private void pesquisarVendas(){
        VendasControl vc = new VendasControl();
     
       if (txtConsulta.getValue() == null){
            JOptionPane.showMessageDialog(this, "Informe a data Inicial!");
            txtConsulta.requestFocus();
        } else if (txtConsultaFim.getValue() == null){
            JOptionPane.showMessageDialog(this, "Informe a data Final!");
            txtConsultaFim.requestFocus();
        } else {
            while ( tmServidores.getRowCount() > 0){
                 tmServidores.removeRow(0);
            }
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
           // SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date dataInicio = (java.util.Date) txtConsulta.getValue();
            System.out.println(String.valueOf(formato.format(dataInicio)));
            java.util.Date dataFim = (java.util.Date) txtConsultaFim.getValue();
            vendas = vc.listarVendasDiadia(String.valueOf(formato.format(dataInicio)), String.valueOf(formato.format(dataFim)));
            //vendas = vc.listarVendas(Date.valueOf(formato.format(dataInicio)));
            String [] campos = new String[] {null, null, null, null, null};
            for (int i = 0; i < vendas.size(); i++){
                tmServidores.addRow(campos);
                tmServidores.setValueAt(vendas.get(i).getCodigo(), i, 0);
                tmServidores.setValueAt(vendas.get(i).getItens(), i, 1);
                tmServidores.setValueAt(vendas.get(i).getDatVenda(), i, 2);
                tmServidores.setValueAt(vendas.get(i).getPedido(), i, 3);
                tmServidores.setValueAt(vendas.get(i).getRecebido(), i, 4);
                tmServidores.setValueAt(vendas.get(i).getTroco(), i, 5);
                tmServidores.setValueAt(vendas.get(i).getValor(), i, 6);//total
            }
            if (vendas.isEmpty()){
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado entre as datas!");
            }
        }
    }
    private void atual(){
    String FormatData = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(System.currentTimeMillis())); 
    //tfDatahoje.setText(FormatData);//passa por parametro a data atual
    txtConsulta.setText(FormatData);
}
    private void atualFim(){
    String FormatData = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(System.currentTimeMillis())); 
    //tfDatahoje.setText(FormatData);//passa por parametro a data atual
    txtConsultaFim.setText(FormatData);
} 
     private void listarCalculoVendas() {
       
        double soma=0;  
        int contador = tmServidores.getRowCount();  
      
      for(int u=0; u<contador; u++){  
            soma =  soma + Double.valueOf(tmServidores.getValueAt(u,6).toString());  
      }   
         ftfTotal.setText(String.valueOf(soma));  
           
    }
    private void listarVendas() {
        VendasControl cli = new VendasControl();
        servidores = cli.listarVendas(("%" + txtConsulta.getText().trim()+ "%"));//tfPesquisaCliente
        mostrarClientes(servidores);
    }
    protected void mostrarClientes(List<VendasBean> clientes){
        while (tmServidores.getRowCount() > 0){
                tmServidores.removeRow(0);
        }
        //if (clientes.size() == 0)usava esse antes
        if (clientes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhuma Venda encontrado!");
        }else{
            //array que armazena as informa�oes no la�o
            String [] campos = new String[] {null, null, null, null};
            for (int i = 0; i < clientes.size(); i++){
            //System.out.println(login.size()+secao.getText());
            
        String conta = String.valueOf(clientes.size()+"  "+"Vendas cadastrados");//conta quantidade de servidores no banco
        contacli.setText(conta);//passa por parametro dentro da label quantos tem no banco
                tmServidores.addRow(campos);
                //tmClientes.setValueAt(clientes.get(i).getCodigo(), i, 0);//indice zero da matriz vector
                tmServidores.setValueAt(clientes.get(i).getCodigo(), i, 0); //nome
                tmServidores.setValueAt(clientes.get(i).getItens(), i, 1);//telefone
                tmServidores.setValueAt(clientes.get(i).getDatVenda(), i, 2);//endereco
                tmServidores.setValueAt(clientes.get(i).getPedido(), i, 3);//bairro
                tmServidores.setValueAt(clientes.get(i).getRecebido(), i, 4);//cidade
                tmServidores.setValueAt(clientes.get(i).getTroco(), i, 5);
                tmServidores.setValueAt(clientes.get(i).getValor(), i, 6);//total
                
                
            }
        }
    }
    protected void tbClientesLinhaSelecionada(JTable tb){
        //(tb.getSelectedRow() != -1)//SE A PESQUISA FOR NOME TEM QUE USAR ESSE
        if (tb.getSelectedRow() != -1){
            //jId.setText(String.valueOf(servidores.get(tb.getSelectedRow()).getId_vigilancia()));//parse int nao precisa mostra ess id pq autoincrement
            listarCalculoVendas();
            //lbFoto.setIcon (new ImageIcon("R:/fotos/"+jTFoto.getText()+".jpg"));
            //lbFoto.setIcon (new ImageIcon("foto/"+txtFoto.getText()));
        } else {
            LimpaCampos();
                        
        }
    }
    
    private void ConsultaExcluir() {
        JPasswordField jpassword = new JPasswordField(); 
        jpassword.requestFocus();
        if (JOptionPane.showConfirmDialog (null, jpassword, "Entre com a senha", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {  
            //System.out.println (new String(jpassword.getPassword()));
            //pega o texto digitado
        //if (jpassword.getText().equals("")){    
        if (jpassword.getText().equals(LerProperties.lerProperties("urlBanco"))){
            //if (lbUsuarios.getText().equals("Andre Gouveia")|| lbUsuarios.getText().equals("Tony")){
            //System.exit(0);
            JOptionPane.showMessageDialog(null,"Lembre-se depois de excluido, não tem como recuperar os dados!");
           
            //mostraCadastro();
            excluiVendas();
        //CapturaFotos d = new CapturaFotos();//cria objeto e armazena na variavel d.show
        //d.show();
       // CapturaImagens d = new CapturaImagens();//cria objeto e armazena na variavel d.show
       // d.show();
       // Cadastrar d = new Cadastrar();//classe Cadastrar
       // d.show();
        
        }else{
            //mostrarVeiculos();
            //Veiculos.tfatualizacao.setText(lbUsuarios.getText());//gravando no label lbatualizacao
            //JOptionPane.showMessageDialog(null,"Assim não da, TCHAU");
            String e ="Atencao";
            JOptionPane.showMessageDialog(null,"Erro"+e," ATENTE PARA SUA SENHA",JOptionPane.WARNING_MESSAGE);
            //dispose();
        //pega o texto gravado em lbUsuarios e seta no campo tfatualizacao
          }
    
        }
        
        
        
              
    }
    private void excluiVendas() {
        if (tbServidores.getSelectedRow() != -1){
                                                                                                     //pega  a linha do Nome selecionado
            int resposta = JOptionPane.showConfirmDialog(this, "Excluir venda selecionada da Tabela?"+"\n"+tbServidores.getValueAt(tbServidores.getSelectedRow(), 0), "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                //CliControl pc = new CliControl();
                VendasControl pc = new VendasControl();
                pc.excluirVendas(servidores.get(tbServidores.getSelectedRow()).getCodigo());
                listarVendas();
            }
        }
    }
    private void excluirVenda(){
        if (tbServidores.getSelectedRow() != -1){
            int resposta = JOptionPane.showConfirmDialog(this, "Excluir venda selecionada?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                VendasControl pc = new VendasControl();
                //pc.excluirVenda(vendas.get(tbServidores.getSelectedRow()).getCodigo()));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btPesquisas;
    private javax.swing.JButton btSomar;
    private javax.swing.JLabel contacli;
    private javax.swing.JFormattedTextField ftfTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable tbServidores;
    private javax.swing.JFormattedTextField txtConsulta;
    private javax.swing.JFormattedTextField txtConsultaFim;
    // End of variables declaration//GEN-END:variables
}
