/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MudaSenha.java
 *
 * Created on 03/10/2013, 00:10:10
 */
package br.com.sisvenda.vendas;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author ROX
 */
public class MudaSenha extends javax.swing.JFrame {

    /** Creates new form MudaSenha */
    public MudaSenha() {
        initComponents();
        setBounds(380,250,413,230);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altera senha");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel3.setText("Altere sua Senha de Acesso");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 10, 180, 15);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        txtLogin.setToolTipText("Nova senha");
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });
        jPanel2.add(txtLogin);
        txtLogin.setBounds(140, 10, 170, 20);

        jLabel1.setText("Nova senha");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 14);

        jLabel2.setText("Confirme a senha");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 40, 110, 14);

        txtPwd.setToolTipText("Confirme a nova senha");
        txtPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPwdFocusLost(evt);
            }
        });
        txtPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPwdKeyTyped(evt);
            }
        });
        jPanel2.add(txtPwd);
        txtPwd.setBounds(140, 40, 170, 20);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel3.add(btnOk);
        btnOk.setBounds(70, 10, 100, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(180, 10, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        // TODO add your handling code here:
        //onClickLocalizarUser();
}//GEN-LAST:event_txtLoginFocusLost

    private void txtPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwdFocusLost
        // TODO add your handling code here:
        //onClickLocalizarUser();
}//GEN-LAST:event_txtPwdFocusLost

    private void txtPwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPwdKeyTyped
        // TODO add your handling code here:
        getRootPane().setDefaultButton(btnOk); //passa o valor para o botao ao ser clicado
}//GEN-LAST:event_txtPwdKeyTyped

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (verificarCampos()){ 
            gravaProperties();
        }else{
            JOptionPane.showMessageDialog(this,"Favor verificar os Campos!","Atenção",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnOkActionPerformed
    protected boolean verificarCampos(){
       
        if (txtLogin.getText().trim().equals("")){//se campo for vazio
            JOptionPane.showMessageDialog(this,"O Campo Senha não pode ser vazio!","Atenção",JOptionPane.INFORMATION_MESSAGE);
            //TxtDestino.requestFocus();
            txtLogin.requestFocus();
            return false;
    }
        if (txtPwd.getText().trim().equals("")){//se campo for vazio
            JOptionPane.showMessageDialog(this,"O Campo Confirme Senha nõa pode ser vazio!","Atenção",JOptionPane.INFORMATION_MESSAGE);
            //TxtDestino.requestFocus();
            txtPwd.requestFocus();
            return false;
    }
        if (!txtLogin.getText().equals(txtPwd.getText().trim())){//se campo nao for  igual a nova senha digitada proseegue
            JOptionPane.showMessageDialog(this,"Os Campos nao confere!","Atenção",JOptionPane.INFORMATION_MESSAGE);
            //TxtDestino.requestFocus();
            txtPwd.setText("");
            txtPwd.requestFocus();
            return false;
        }
          
        return true;
    }
    //grava no arquivo.properties junto ao projeto
    public void gravaProperties(){
 
        try{
 
            //File file = new File("C:\\cria\\arquivo.properties");
            File file = new File("arquivo.properties");//grava local do jar
 
            Properties props = new Properties();
           // props.setProperty("urlBanco", "localhost");//senha
            props.setProperty("urlBanco", txtPwd.getText());//pega o que vier do campo senha
 
            FileOutputStream fos = new FileOutputStream(file);
 
            props.store(fos, "#Meu arquivo properties");
 
            fos.flush();
            fos.close();
            JOptionPane.showMessageDialog(null,"Senha alterada com sucesso!"+"\n"+"Memorize sua nova senha"+"\n"+txtPwd.getText(),"Alterou",JOptionPane.WARNING_MESSAGE);
            this.dispose();
        }catch(Exception x){
            //x.printStackTrace();
            JOptionPane.showMessageDialog(null,"Erro!","Exceção?"+x,JOptionPane.WARNING_MESSAGE);
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
}//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MudaSenha().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables
}
