/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.Pedidos;

import br.com.Controle.CliBean;
import br.com.Controle.CliControl;
import java.util.List;

/**
 *
 * @author digao
 */
public class PegaCliente extends javax.swing.JFrame{

    private List<CliBean> pedido;
    /**
     * Creates new form PegaCliente
     */
    public PegaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btPesquisa = new javax.swing.JButton();
        llbData = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        txtEntrega = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        btTransporte = new javax.swing.JButton();

        jLabel1.setText("Pesquisar:");

        btPesquisa.setText(".....");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        llbData.setText("Data");

        txtEndereco.setText("jTextField3");

        txtEntrega.setText("jTextField5");

        txtTelefone.setText("jTextField4");

        txtNome.setText("jTextField2");

        txtId.setText("jTextField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefone)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        txtPesquisa.setText("jTextField1");

        btTransporte.setText("Sair");
        btTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(btTransporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(llbData, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(llbData)
                    .addComponent(btPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTransporte))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        // TODO add your handling code here:
        //tipoPesquisa = "Matricula";
        //listarClientes();//pesquisa por nome
        listarClientesTelefone();//pesquisa por telefone

    }//GEN-LAST:event_btPesquisaActionPerformed
 private boolean listarClientesTelefone() {
       
        CliControl cli = new CliControl();
        //--usado antespedido = cli.listarCliente("%" + txtPesquisa.getText().trim() + "%");//tfPesquisaCliente
        pedido = cli.listarPedidos("%" + txtPesquisa.getText().trim() + "%");
        //listarPedidos
        //mostrarVeiculos(pedido);
        for (int i = 0; i < pedido.size(); i++){
           //-- cbPedidos.addItem(pedido.get(i).getNome_vigi());
            txtId.setText(String.valueOf(pedido.get(i).getId_vigilancia()));
            txtNome.setText(pedido.get(i).getNome_vigi().toString());
            txtTelefone.setText(pedido.get(i).getTelefone_vigi().toString());
            txtEndereco.setText(pedido.get(i).getPosto_vigi());
            txtEntrega.setText(String.valueOf(pedido.get(i).getEntrega()));
           //  Pedidos.jIdCliente.setText(String.valueOf(pedido.get(i).getId_vigilancia()));
           //  Pedidos.txtNome.setText(pedido.get(i).getNome_vigi());
           //  Pedidos.txtTelefone.setText(pedido.get(i).getTelefone_vigi());
           //  Pedidos.txtEndereco.setText(pedido.get(i).getPosto_vigi());
          //   Pedidos.txtEntrega.setText(String.valueOf(pedido.get(i).getEntrega()));
            //--transporta para pedidos//--Pedidos.txtTelefone.setText(pedido.get(i).getTelefone_vigi());
            //cbPedidos.addItem(pedido.get(i).getTelefone_vigi());
            //String conta = String.valueOf("Total de "+ cliente.size()+"  "+"Clientes cadastrados");//conta quantidade de servidores no banco
            //contacli.setText(conta
            // jId.setText(String.valueOf(c.getIdindex()));
           // pedido.clear();
        }
        
       return true;
    }
    
           
           
    
    
    private void btTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransporteActionPerformed

        Pedidos action = new Pedidos ();
       
        

    }//GEN-LAST:event_btTransporteActionPerformed

public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PegaCliente().setVisible(true);
                 //new Principal().se(true);
               // new PegaCliente().setVisible(true);
               //new Pedidos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton btTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel llbData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
