package br.com.Acessobd;

import br.com.Util.CalendarComboBox;
import br.com.Util.DadosPassados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * FCadFuncao.java
 *
 * Created on 6 de Dezembro de 2005, 13:13
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FCadFuncao extends javax.swing.JFrame {
    public static java.sql.Statement stmt;
     
    
    /** Creates new form FCadFuncao */
    public FCadFuncao() {
        initComponents();
        atualizaagora();
        setBounds(350,150,510,510);
    }
    private void atualizaagora(){
    String FormatData = new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis()));
    //tfDatahoje.setText(FormatData);//passa por parametro a data atual
    //tfDataAtual.setText(FormatData);
    tfdata.setText(FormatData);
}
    private void escolhaData() throws ParseException{
        String retorno = JOptionPane.showInputDialog(null, "Data de Nascimento: ","Data",JOptionPane.OK_OPTION);  
        Date data = new SimpleDateFormat("dd/MM/yyyy").parse(retorno);  
        System.out.println(data); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        tfdata = new javax.swing.JTextField();
        tfqtd = new javax.swing.JTextField();
        tfvalor = new javax.swing.JTextField();
        SomaValor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        somaFrame = new javax.swing.JButton();
        ccb = new CalendarComboBox(true);
        tfdatasoma = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Diárias ASTEC-PB v1.0");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Cadastro de Funções");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 150, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel2.setText("Pedido:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 50, 50, 14);

        txtNome.setToolTipText("Numero do Pedido");
        jPanel2.add(txtNome);
        txtNome.setBounds(20, 70, 160, 20);

        tfdata.setToolTipText("Data do dia");
        tfdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfdataMouseClicked(evt);
            }
        });
        jPanel2.add(tfdata);
        tfdata.setBounds(20, 140, 100, 20);

        tfqtd.setText("1");
        tfqtd.setToolTipText("Quantidade");
        jPanel2.add(tfqtd);
        tfqtd.setBounds(20, 110, 100, 20);

        tfvalor.setToolTipText("Valor da Venda");
        jPanel2.add(tfvalor);
        tfvalor.setBounds(210, 70, 130, 40);

        SomaValor.setText("Consultas de Vendas atual");
        SomaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaValorActionPerformed(evt);
            }
        });
        jPanel2.add(SomaValor);
        SomaValor.setBounds(10, 180, 190, 23);

        jLabel3.setText("Qtd");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 110, 18, 14);

        jLabel4.setText("Data");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 140, 23, 14);

        jLabel5.setText("valor da venda");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 50, 90, 14);

        somaFrame.setText("Soma anteriores");
        somaFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaFrameActionPerformed(evt);
            }
        });
        jPanel2.add(somaFrame);
        somaFrame.setBounds(210, 180, 130, 23);

        ccb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ccbMouseClicked(evt);
            }
        });
        ccb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbActionPerformed(evt);
            }
        });
        jPanel2.add(ccb);
        ccb.setBounds(210, 120, 130, 20);
        jPanel2.add(tfdatasoma);
        tfdatasoma.setBounds(210, 150, 130, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 380, 210);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(70, 10, 110, 23);

        jButton2.setText("Cancelar");
        jPanel3.add(jButton2);
        jButton2.setBounds(190, 10, 110, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 280, 380, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        if(txtNome.getText().trim().length() == 0){
         JOptionPane.showMessageDialog(null,"Preencha o Campo Nome","ATEN��O",JOptionPane.WARNING_MESSAGE);
         }else{
        ClassCadVenda funcao = new ClassCadVenda();
        funcao.setNome(txtNome.getText());
        funcao.setData(tfdata.getText());
        funcao.setQtd(tfqtd.getText());
        funcao.setValor(tfvalor.getText());
        funcao.incluiFuncao();
         
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void Soma() throws SQLException{
        
        final String DRIVER = "sun.jdbc.odbc.JdbcOdbcDriver";  
        //final String URL = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ=C:/bancoAccess/meuBanco.mdb"; // caminho onde está o banco  
        final String URL = "jdbc:odbc:dog";
        Connection conn = null; 
        atualizaagora();
        String sql = ("SELECT SUM(valor) as Total FROM vendas WHERE dia = '" + tfdatasoma.getText()+ "'");
        //String sql = ("SELECT SUM(valor) as Total FROM vendas WHERE dia = '" + FCadFuncao.tfdata.getText() + "'");
        Double total = null;  //SELECT SUM(estoque) FROM chave where tipo = ('TETRA')"
        try {  
            Class.forName(DRIVER);  
            conn = DriverManager.getConnection(URL);  
            JOptionPane.showMessageDialog(null, "Conexao realizada com sucesso");  
            Statement st = conn.createStatement();  
            ResultSet rs = st.executeQuery(sql);  
            while(rs.next()){ // o resultset é como um cursor que retorna o resultado da sua query e pode retornar de 0 a n linhas   
                
                total = rs.getDouble("Total"); // guarda na variavel o retorno do select  
            
                       
            }  
              JOptionPane.showMessageDialog(null, "Total de Vendas do dia"+"\n"+tfdatasoma.getText()+"\n"+total+"\n"); 
              //System.out.println( sdf.format(hoje));
              
              
        } catch (ClassNotFoundException erro) {  
            JOptionPane.showMessageDialog(null, "Driver JDBC-ODBC não encontrado!");  
        } catch (SQLException e) {  
            JOptionPane.showMessageDialog(null, "Problemas na conexao");  
            e.printStackTrace();  
        } finally {  
            try {  
                conn.close();  
            } catch (SQLException e) {  
                e.printStackTrace();  
            }  
        }  
  
    }

    private void SomaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaValorActionPerformed
        Somavalor somatoria = new Somavalor(); //.setVisible(true);
        somatoria.Soma();//chamo somente o metodo que faz todo o trabalho na classe
    }//GEN-LAST:event_SomaValorActionPerformed

    private void somaFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaFrameActionPerformed
        try {
            Soma();
        } catch (SQLException ex) {
            Logger.getLogger(FCadFuncao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_somaFrameActionPerformed

    private void tfdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdataMouseClicked
        try {
            escolhaData();
        } catch (ParseException ex) {
            Logger.getLogger(FCadFuncao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tfdataMouseClicked

    private void ccbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccbMouseClicked
        
}//GEN-LAST:event_ccbMouseClicked

    private void ccbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbActionPerformed
        DadosPassados dados = new DadosPassados();//cria o obejeto que vai receber os valores atributos
        //pega o texto digitado deste campo convertido em string do ccbBox
        dados.setData((String)ccb.getSelectedItem());
        //ccb.getSelectedItem().toString();
        tfdatasoma.setText(dados.getData());
    }//GEN-LAST:event_ccbActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadFuncao().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SomaValor;
    private javax.swing.JComboBox ccb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton somaFrame;
    public static javax.swing.JTextField tfdata;
    private javax.swing.JTextField tfdatasoma;
    private javax.swing.JTextField tfqtd;
    private javax.swing.JTextField tfvalor;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    
}
